# Generated by Django 6.0.3 on 2026-03-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_comprador_pedido_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(max_length=150),
        ),
    ]
