# Generated by Django 6.0.3 on 2026-03-18 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_loja_slug_alter_loja_email_alter_loja_telefone'),
        ('produtos', '0004_pedido_endereco_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('confirmacao', 'Aguardando confirmação'), ('pago', 'Pago')], default='aguardando', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RegiaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes_entrega', to='lojas.loja')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='regiao_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.regiaoentrega'),
        ),
    ]
