# Generated by Django 6.0.3 on 2026-03-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_loja_slug_alter_loja_email_alter_loja_telefone'),
        ('produtos', '0005_pedido_status_pagamento_pedido_valor_frete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='regiao_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento_entrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua_entrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='ConfigFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_origem', models.CharField(blank=True, max_length=20, null=True)),
                ('rua_origem', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_origem', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento_origem', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('km_max_local', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('valor_excedente', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('valor_fora_estado', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('retirada_loja', models.BooleanField(default=True)),
                ('entrega_ativa', models.BooleanField(default=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_frete', to='lojas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='FaixaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('km_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_frete', to='lojas.loja')),
            ],
        ),
        migrations.DeleteModel(
            name='RegiaoEntrega',
        ),
    ]
