# Generated by Django 6.0.3 on 2026-03-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_pedido_regiao_entrega_pedido_bairro_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfrete',
            name='banco_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='nome_recebedor_pix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_cartao',
            field=models.CharField(blank=True, choices=[('', 'Não se aplica'), ('debito', 'Débito'), ('credito', 'Crédito')], default='', max_length=20),
        ),
    ]
