# Generated by Django 6.0.3 on 2026-03-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_configfrete_banco_pix_configfrete_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfrete',
            name='mp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='mp_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='mp_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='mp_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_ticket_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('confirmacao', 'Aguardando confirmação'), ('pago', 'Pago'), ('recusado', 'Recusado')], default='aguardando', max_length=20),
        ),
    ]
