# Generated by Django 6.0.3 on 2026-03-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_configfrete_mp_access_token_configfrete_mp_connected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_envio', 'Aguardando envio'), ('enviado', 'Enviado'), ('saiu_entrega', 'Saiu para entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
