# Generated by Django 6.0.3 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual_promocao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_novo',
            field=models.BooleanField(default=False),
        ),
    ]
