# Generated by Django 6.0.3 on 2026-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produto_em_destaque_produto_percentual_promocao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='em_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprador',
            name='percentual_promocao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprador',
            name='produto_novo',
            field=models.BooleanField(default=False),
        ),
    ]
