# Generated by Django 6.0.3 on 2026-03-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_comprador_em_destaque_comprador_percentual_promocao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='em_destaque',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='percentual_promocao',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='produto_novo',
        ),
    ]
