# Generated by Django 6.0.3 on 2026-04-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
