# Generated by Django 6.0.3 on 2026-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produto_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfrete',
            name='valor_mesma_cidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configfrete',
            name='valor_mesmo_estado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
