# Generated by Django 6.0.3 on 2026-04-18 03:00

import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_configfrete_valor_mesma_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=produtos.models.upload_produto_imagem),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(upload_to=produtos.models.upload_produto_imagem_extra),
        ),
    ]
