# Generated by Django 6.0.3 on 2026-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
