# Generated by Django 6.0.3 on 2026-03-25 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_loja_slug_alter_loja_email_alter_loja_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='telefone',
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_botao_link',
            field=models.CharField(blank=True, default='#produtos', max_length=255),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_botao_texto',
            field=models.CharField(blank=True, default='Comprar agora', max_length=60),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_cor_fim',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_cor_inicio',
            field=models.CharField(blank=True, default='#16a34a', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_subtitulo',
            field=models.CharField(blank=True, default='Compre com praticidade e encontre tudo em um só lugar.', max_length=220),
        ),
        migrations.AddField(
            model_name='loja',
            name='banner_titulo',
            field=models.CharField(blank=True, default='+ PRODUTOS\nNA SUA LOJA', max_length=120),
        ),
        migrations.AddField(
            model_name='loja',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='lojas/'),
        ),
        migrations.AddField(
            model_name='loja',
            name='texto_busca',
            field=models.CharField(blank=True, default='O que você procura?', max_length=120),
        ),
        migrations.AlterField(
            model_name='loja',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
