# Generated by Django 6.0.3 on 2026-03-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_remove_loja_ativa_remove_loja_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='email_comercial',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_botao_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_botao_texto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_cor_fim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_cor_inicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_subtitulo',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_titulo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='texto_busca',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
