# Generated by Django 6.0.3 on 2026-03-26 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0004_loja_ativa_loja_cnpj_loja_email_comercial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'ordering': ['nome'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='loja',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='data_ultimo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='data_vencimento_licenca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='status_licenca',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('vencida', 'Vencida')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_botao_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='banner_titulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='texto_busca',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
