# Generated by Django 6.0.3 on 2026-03-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_alter_loja_options_loja_atualizado_em_loja_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='banner_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
