# Generated by Django 6.0.3 on 2026-03-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0006_loja_banner_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='aceitar_cartao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='aceitar_pix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='aceitar_whatsapp_financeiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='nome_recebedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='observacoes_licenca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='pix_copia_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='plano_licenca',
            field=models.CharField(default='Plano Básico', max_length=100),
        ),
        migrations.AddField(
            model_name='loja',
            name='valor_licenca',
            field=models.DecimalField(decimal_places=2, default=49.9, max_digits=10),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp_financeiro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
