# Generated by Django 6.0.3 on 2026-03-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0007_loja_aceitar_cartao_loja_aceitar_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pagamento', models.CharField(choices=[('pix', 'Pix'), ('checkout', 'Checkout')], max_length=20)),
                ('external_reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='criado', max_length=20)),
                ('mp_payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=120, null=True)),
                ('mp_init_point', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('ticket_url', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_licenca', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Pagamento de Licença',
                'verbose_name_plural': 'Pagamentos de Licença',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
