# Generated by Django 6.0.3 on 2026-03-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0008_pagamentolicenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tipo_loja',
            field=models.CharField(choices=[('roupas', 'Roupas'), ('comida', 'Comida'), ('cosmeticos', 'Cosméticos'), ('eletronicos', 'Eletrônicos'), ('acessorios', 'Acessórios'), ('servicos', 'Serviços'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Tipo da loja'),
        ),
    ]
