# Generated by Django 6.0.3 on 2026-04-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0009_loja_tipo_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='pagamentolicenca',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='loja',
            name='plano_licenca',
        ),
        migrations.RemoveField(
            model_name='pagamentolicenca',
            name='plano_nome',
        ),
    ]
