# Generated by Django 6.0.3 on 2026-04-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0010_alter_loja_options_alter_pagamentolicenca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentolicenca',
            name='plano_nome',
            field=models.CharField(default='Plano padrão', max_length=100),
        ),
    ]
