# Generated by Django 6.0.3 on 2026-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0011_pagamentolicenca_plano_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='dominio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
