# Generated by Django 6.0.3 on 2026-04-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0012_loja_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cobranca_automatica_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loja',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='mp_preapproval_init_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='mp_preapproval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='valor_licenca',
            field=models.DecimalField(decimal_places=2, default=59.9, max_digits=10),
        ),
    ]
