from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('lojas','0013_loja_cobranca_automatica_ativa_and_more')]
    operations = [
        migrations.CreateModel(name='Processo', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('nome',models.CharField(max_length=160)),('codigo',models.CharField(blank=True,max_length=40)),('objetivo',models.TextField(blank=True)),('responsavel',models.CharField(blank=True,max_length=120)),('entradas',models.TextField(blank=True)),('saidas',models.TextField(blank=True)),('riscos',models.TextField(blank=True)),('status',models.CharField(choices=[('ativo','Ativo'),('revisao','Em revisão'),('inativo','Inativo')],default='ativo',max_length=20)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))], options={'ordering':['nome'],'unique_together':{('loja','codigo')}}),
        migrations.CreateModel(name='Indicador', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('nome',models.CharField(max_length=160)),('unidade',models.CharField(default='%',max_length=30)),('meta',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('sentido',models.CharField(choices=[('maior','Maior'),('menor','Menor')],default='maior',max_length=10)),('periodicidade',models.CharField(choices=[('mensal','Mensal'),('semanal','Semanal'),('diario','Diário')],default='mensal',max_length=20)),('responsavel',models.CharField(blank=True,max_length=120)),('ativo',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('processo',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.processo'))]),
        migrations.CreateModel(name='MedicaoIndicador', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('periodo',models.DateField()),('valor',models.DecimalField(decimal_places=2,max_digits=12)),('observacao',models.CharField(blank=True,max_length=255)),('indicador',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='medicoes',to='gestao.indicador')),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))], options={'ordering':['-periodo'],'unique_together':{('indicador','periodo')}}),
        migrations.CreateModel(name='PlanoAcao', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('origem',models.CharField(blank=True,max_length=120)),('o_que',models.TextField(verbose_name='O que')),('por_que',models.TextField(blank=True,verbose_name='Por quê')),('onde',models.CharField(blank=True,max_length=150)),('quem',models.CharField(blank=True,max_length=120)),('quando',models.DateField(blank=True,null=True)),('como',models.TextField(blank=True)),('quanto',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('status',models.CharField(choices=[('aberto','Aberto'),('andamento','Em andamento'),('concluido','Concluído'),('atrasado','Atrasado')],default='aberto',max_length=20)),('prioridade',models.CharField(choices=[('baixa','Baixa'),('media','Média'),('alta','Alta'),('critica','Crítica')],default='media',max_length=10)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
        migrations.CreateModel(name='NaoConformidade', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('codigo',models.CharField(blank=True,max_length=40)),('titulo',models.CharField(max_length=180)),('descricao',models.TextField()),('causa_raiz',models.TextField(blank=True)),('correcao',models.TextField(blank=True)),('responsavel',models.CharField(blank=True,max_length=120)),('prazo',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('aberta','Aberta'),('analise','Em análise'),('acao','Ação em curso'),('encerrada','Encerrada')],default='aberta',max_length=20)),('severidade',models.IntegerField(default=3)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('processo',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.processo'))]),
        migrations.CreateModel(name='DocumentoGestao', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('codigo',models.CharField(blank=True,max_length=40)),('titulo',models.CharField(max_length=180)),('tipo',models.CharField(choices=[('politica','Política'),('procedimento','Procedimento'),('instrucao','Instrução de trabalho'),('registro','Registro'),('manual','Manual')],default='procedimento',max_length=20)),('versao',models.CharField(default='1.0',max_length=20)),('responsavel',models.CharField(blank=True,max_length=120)),('arquivo',models.FileField(blank=True,null=True,upload_to='gestao/documentos/')),('conteudo',models.TextField(blank=True)),('aprovado',models.BooleanField(default=False)),('proxima_revisao',models.DateField(blank=True,null=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
        migrations.CreateModel(name='Auditoria', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('escopo',models.TextField(blank=True)),('auditor',models.CharField(blank=True,max_length=120)),('data',models.DateField()),('status',models.CharField(choices=[('planejada','Planejada'),('andamento','Em andamento'),('concluida','Concluída')],default='planejada',max_length=20)),('resultado',models.TextField(blank=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
        migrations.CreateModel(name='RequisitoISO', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('norma',models.CharField(default='ISO 9001:2015',max_length=40)),('clausula',models.CharField(max_length=20)),('titulo',models.CharField(max_length=180)),('status',models.CharField(choices=[('nao_iniciado','Não iniciado'),('andamento','Em andamento'),('conforme','Conforme'),('na','Não aplicável')],default='nao_iniciado',max_length=20)),('evidencia',models.TextField(blank=True)),('responsavel',models.CharField(blank=True,max_length=120)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))], options={'ordering':['clausula']}),
        migrations.CreateModel(name='RiscoFMEA', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('modo_falha',models.CharField(max_length=180)),('efeito',models.TextField(blank=True)),('causa',models.TextField(blank=True)),('severidade',models.PositiveSmallIntegerField(default=1)),('ocorrencia',models.PositiveSmallIntegerField(default=1)),('deteccao',models.PositiveSmallIntegerField(default=1)),('acao',models.TextField(blank=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('processo',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='fmeas',to='gestao.processo'))]),
        migrations.CreateModel(name='RegistroProducao', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('data',models.DateField()),('linha',models.CharField(max_length=120)),('tempo_planejado',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('tempo_operando',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('quantidade_total',models.PositiveIntegerField(default=0)),('quantidade_boa',models.PositiveIntegerField(default=0)),('ciclo_ideal',models.DecimalField(decimal_places=4,default=0,max_digits=10)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
        migrations.CreateModel(name='IdeiaMelhoria', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('descricao',models.TextField()),('autor',models.CharField(blank=True,max_length=120)),('status',models.CharField(choices=[('nova','Nova'),('avaliacao','Em avaliação'),('aprovada','Aprovada'),('implantada','Implantada')],default='nova',max_length=20)),('votos',models.PositiveIntegerField(default=0)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
    ]
