from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('gestao','0001_initial'),('lojas','0013_loja_cobranca_automatica_ativa_and_more'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Setor',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('nome',models.CharField(max_length=120)),('descricao',models.TextField(blank=True)),('gestor',models.CharField(blank=True,max_length=120)),('ativo',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))],options={'ordering':['nome'],'unique_together':{('loja','nome')}}),
      migrations.CreateModel(name='Colaborador',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('cargo',models.CharField(blank=True,max_length=120)),('matricula',models.CharField(blank=True,max_length=60)),('pontos',models.PositiveIntegerField(default=0)),('nivel',models.PositiveIntegerField(default=1)),('ativo',models.BooleanField(default=True)),('criado_em',models.DateTimeField(auto_now_add=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='colaboradores_gestao',to='lojas.loja')),('setor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.setor')),('usuario',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='perfil_colaborador',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='Tarefa',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('descricao',models.TextField(blank=True)),('inicio',models.DateField(blank=True,null=True)),('fim',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('backlog','Backlog'),('fazer','A fazer'),('andamento','Em andamento'),('revisao','Em revisão'),('concluida','Concluída')],default='fazer',max_length=20)),('prioridade',models.CharField(choices=[('baixa','Baixa'),('media','Média'),('alta','Alta'),('critica','Crítica')],default='media',max_length=10)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('responsavel',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.colaborador')),('setor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.setor'))]),
      migrations.CreateModel(name='NotaWorkspace',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(blank=True,max_length=120)),('conteudo',models.TextField()),('cor',models.CharField(default='amarelo',max_length=20)),('fixada',models.BooleanField(default=False)),('autor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('setor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.setor'))]),
      migrations.CreateModel(name='ProjetoQualidade',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('ferramenta',models.CharField(choices=[('pdca','PDCA'),('5w2h','5W2H'),('ishikawa','Ishikawa'),('5porques','5 Porquês'),('pareto','Pareto'),('sipoc','SIPOC'),('masp','MASP'),('5s','5S')],max_length=20)),('titulo',models.CharField(max_length=180)),('problema',models.TextField(blank=True)),('responsavel',models.CharField(blank=True,max_length=120)),('inicio',models.DateField(blank=True,null=True)),('fim',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('rascunho','Rascunho'),('andamento','Em andamento'),('concluido','Concluído')],default='rascunho',max_length=20)),('dados',models.JSONField(blank=True,default=dict)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='Treinamento',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('descricao',models.TextField(blank=True)),('categoria',models.CharField(default='Qualidade',max_length=80)),('conteudo',models.TextField(blank=True)),('pontos',models.PositiveIntegerField(default=100)),('obrigatorio',models.BooleanField(default=False)),('ativo',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='TrilhaColaborador',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('status',models.CharField(choices=[('pendente','Pendente'),('andamento','Em andamento'),('concluido','Concluído')],default='pendente',max_length=20)),('nota',models.DecimalField(blank=True,decimal_places=2,max_digits=5,null=True)),('concluido_em',models.DateTimeField(blank=True,null=True)),('colaborador',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trilhas',to='gestao.colaborador')),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('treinamento',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='gestao.treinamento'))],options={'unique_together':{('colaborador','treinamento')}}),
      migrations.CreateModel(name='TentativaJogo',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('jogo',models.CharField(max_length=40)),('pontuacao',models.PositiveIntegerField(default=0)),('total',models.PositiveIntegerField(default=0)),('detalhes',models.JSONField(blank=True,default=dict)),('colaborador',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tentativas',to='gestao.colaborador')),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='RegistroLGPD',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('tipo',models.CharField(choices=[('consentimento','Consentimento'),('privacidade','Ciência de privacidade'),('treinamento','Treinamento LGPD'),('solicitacao','Solicitação de titular')],max_length=20)),('finalidade',models.CharField(blank=True,max_length=255)),('base_legal',models.CharField(blank=True,max_length=120)),('status',models.CharField(default='registrado',max_length=30)),('detalhes',models.TextField(blank=True)),('ip_hash',models.CharField(blank=True,max_length=64)),('registrado_em',models.DateTimeField(auto_now_add=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('usuario',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
    ]
