from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('gestao','0002_b2b_workspace_gamificacao_lgpd')]
    operations=[
      migrations.CreateModel(name='AtividadeTratamento',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('nome',models.CharField(max_length=180)),('area',models.CharField(blank=True,max_length=120)),('finalidade',models.TextField()),('base_legal',models.CharField(max_length=120)),('titulares',models.CharField(blank=True,max_length=180)),('dados_pessoais',models.TextField(blank=True)),('compartilhamentos',models.TextField(blank=True)),('retencao',models.CharField(blank=True,max_length=120)),('medidas_seguranca',models.TextField(blank=True)),('responsavel',models.CharField(blank=True,max_length=120)),('risco',models.CharField(choices=[('baixo','Baixo'),('medio','Médio'),('alto','Alto')],default='medio',max_length=10)),('ativo',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='SolicitacaoTitular',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('protocolo',models.CharField(blank=True,max_length=40)),('titular',models.CharField(max_length=160)),('contato',models.CharField(blank=True,max_length=160)),('tipo',models.CharField(choices=[('acesso','Acesso'),('correcao','Correção'),('eliminacao','Eliminação'),('portabilidade','Portabilidade'),('oposicao','Oposição/ revisão')],max_length=20)),('descricao',models.TextField(blank=True)),('prazo',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('recebida','Recebida'),('analise','Em análise'),('respondida','Respondida'),('encerrada','Encerrada')],default='recebida',max_length=20)),('resposta',models.TextField(blank=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='IncidentePrivacidade',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=180)),('ocorrido_em',models.DateTimeField()),('descricao',models.TextField()),('dados_afetados',models.TextField(blank=True)),('titulares_afetados',models.PositiveIntegerField(default=0)),('risco',models.CharField(choices=[('baixo','Baixo'),('medio','Médio'),('alto','Alto')],default='medio',max_length=10)),('contencao',models.TextField(blank=True)),('avaliacao_anpd',models.TextField(blank=True)),('status',models.CharField(choices=[('aberto','Aberto'),('contido','Contido'),('investigacao','Investigação'),('encerrado','Encerrado')],default='aberto',max_length=20)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))]),
      migrations.CreateModel(name='ConquistaColaborador',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('codigo',models.CharField(max_length=60)),('titulo',models.CharField(max_length=120)),('descricao',models.CharField(blank=True,max_length=255)),('concedida_em',models.DateTimeField(auto_now_add=True)),('colaborador',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='conquistas',to='gestao.colaborador')),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))],options={'unique_together':{('colaborador','codigo')}}),
    ]
