from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('gestao','0004_perfis_ranking_social'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='Notificacao',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=160)),('mensagem',models.CharField(blank=True,max_length=500)),('link',models.CharField(blank=True,max_length=255)),('lida',models.BooleanField(default=False)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('usuario',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notificacoes_gestao',to=settings.AUTH_USER_MODEL))],options={'ordering':['-criado_em']}),
      migrations.CreateModel(name='ComentarioTarefa',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('texto',models.TextField()),('autor',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('tarefa',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comentarios',to='gestao.tarefa'))],options={'ordering':['criado_em']}),
      migrations.CreateModel(name='RegistroAuditoriaSistema',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('acao',models.CharField(max_length=80)),('objeto',models.CharField(blank=True,max_length=120)),('descricao',models.CharField(blank=True,max_length=500)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('usuario',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-criado_em']}),
      migrations.CreateModel(name='MetaEquipe',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('titulo',models.CharField(max_length=160)),('descricao',models.TextField(blank=True)),('meta_pontos',models.PositiveIntegerField(default=500)),('inicio',models.DateField(blank=True,null=True)),('fim',models.DateField(blank=True,null=True)),('ativa',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('setor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='gestao.setor'))]),
    ]
