from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies=[('gestao','0005_colaboracao_governanca')]
    operations=[
        migrations.AddField(model_name='colaborador',name='papel',field=models.CharField(choices=[('colaborador','Colaborador'),('gestor_setor','Gestor de setor'),('gestor_empresa','Gestor da empresa')],default='colaborador',max_length=20)),
        migrations.AddField(model_name='colaborador',name='email_notificacoes',field=models.BooleanField(default=True)),
        migrations.AddField(model_name='trilhacolaborador',name='prazo',field=models.DateField(blank=True,null=True)),
        migrations.AddField(model_name='treinamento',name='video_url',field=models.URLField(blank=True)),
        migrations.AddField(model_name='treinamento',name='nota_minima',field=models.PositiveSmallIntegerField(default=70)),
        migrations.CreateModel(name='EtapaTreinamento',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('ordem',models.PositiveIntegerField(default=1)),('titulo',models.CharField(max_length=180)),('descricao',models.TextField(blank=True)),('video_url',models.URLField(blank=True)),('material',models.FileField(blank=True,null=True,upload_to='gestao/treinamentos/')),('pergunta',models.CharField(blank=True,max_length=300)),('resposta_esperada',models.CharField(blank=True,max_length=300)),('pontos',models.PositiveIntegerField(default=20)),('obrigatoria',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('treinamento',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='etapas',to='gestao.treinamento'))],options={'ordering':['treinamento','ordem'],'unique_together':{('treinamento','ordem')}}),
        migrations.CreateModel(name='ProgressoEtapa',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('concluida',models.BooleanField(default=False)),('resposta',models.CharField(blank=True,max_length=500)),('concluida_em',models.DateTimeField(blank=True,null=True)),('colaborador',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='progresso_etapas',to='gestao.colaborador')),('etapa',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='progressos',to='gestao.etapatreinamento')),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja'))],options={'unique_together':{('colaborador','etapa')}}),
        migrations.CreateModel(name='PreferenciaNotificacao',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('email_avisos',models.BooleanField(default=True)),('aviso_7_dias',models.BooleanField(default=True)),('aviso_1_dia',models.BooleanField(default=True)),('aviso_atraso',models.BooleanField(default=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('usuario',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='preferencias_alertas',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='AlertaEnviado',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('criado_em',models.DateTimeField(auto_now_add=True)),('atualizado_em',models.DateTimeField(auto_now=True)),('chave',models.CharField(max_length=180)),('canal',models.CharField(default='plataforma',max_length=20)),('enviado_em',models.DateTimeField(auto_now_add=True)),('loja',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lojas.loja')),('usuario',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))],options={'unique_together':{('loja','usuario','chave','canal')}}),
    ]
