# Generated by Django 6.0.3 on 2026-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0016_construtor_treinamentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapatreinamento",
            name="pergunta",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
